repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.2" # ruff 버전에 맞게 수정
    hooks:
      - id: ruff
        args: ["--fix"] # 자동 수정 적용

  - repo: https://github.com/psf/black
    rev: "25.1.0" # black 버전에 맞게
    hooks:
      - id: black
        language_version: python3.11
